settings:
  title: 'Status Page'
  url: 'https://status.pollux.gg' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: cdn # unique identifier
    name: CDN
    description: 'Content Delivery' # default=empty
    url: 'https://cdn.pollux.gg/favicon.png' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false

  - id: dev-dash
    name: DEV Dash
    description: 'Beta Dashboard'
    url: 'https://hijola.pollux.gg/commands'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: dash
    name: Live Dash
    description: 'Public Dashboard'
    url: 'https://beta.pollux.gg/commands'
    method: GET
    expectStatus: 200
    followRedirect: true
    
  - id: vanilla
    name: Vanilla Dash
    description: 'Vanilla Dashboard'
    url: 'https://vanilla.pollux.gg/commands'
    method: GET
    expectStatus: 200
    followRedirect: true
    
  - id: test
    name: Test
    description: 'Bot Cluster 0'
    url: 'botswarm:ALDEBARAN:66'
    method: GET
    expectStatus: 200
    followRedirect: true
